<script lang="ts">
  import {
    bundle, cohort, patientsById, selectedPatientId, selectedPhenotypeId,
    advancedView, searchedPhenotypeForPatients, phenotypesById,
  } from '../store'
  import { generateCohort } from '../cohort'
  import { phenotypeHue } from '../palette'
  import { displayedDominant } from '../dominant'
  import PatientMap from '../patient/PatientMap.svelte'
  import PatientBrowser from '../patient/PatientBrowser.svelte'
  import ProfileBar from '../patient/ProfileBar.svelte'
  import ContributingCodes from '../patient/ContributingCodes.svelte'
  import NeighborRibbon from '../patient/NeighborRibbon.svelte'
  import ConditionSearch from '../atlas/ConditionSearch.svelte'

  // Initial batch size; adaptive sizing in cohort.ts may grow this.
  const COHORT_N = 1500
  const NEIGHBORS = 8

  // Visible-in-current-mode patients (basic = clean only, advanced = all).
  // We default the detail panel selection to one of these so basic mode
  // never opens onto a hidden messy patient.
  $: allPatients = $cohort?.patients ?? []
  $: visiblePatients = $advancedView
    ? allPatients
    : allPatients.filter((p) => p.isClean)
  $: current = (() => {
    if ($selectedPatientId) {
      const sel = $patientsById.get($selectedPatientId)
      if (sel && ($advancedView || sel.isClean)) return sel
    }
    return visiblePatients[0] ?? null
  })()
  $: if (current && $selectedPatientId !== current.id) selectedPatientId.set(current.id)

  $: phenotypes = $bundle?.phenotypes.phenotypes ?? []
  // Color the patient-panel selection dot to match the patient's atlas dot
  // (which is colored by displayedDominant). Keeps the "this detail is
  // about that dot" link consistent across the two panels and avoids
  // naming a dead/mixed phenotype in basic mode.
  $: dotColor = current
    ? $phenotypeHue(displayedDominant(current.theta, phenotypes, $advancedView))
    : 'var(--accent)'

  // Background-click closes the disclosure popover so it dismisses with a
  // click anywhere outside, not only by re-clicking the link.
  let whatIsEl: HTMLDetailsElement
  let whatIsOpen = false

  function regenCohort() {
    if (!$bundle || !$cohort) return
    // Derive next seed from the current cohort, not a local counter:
    // tab unmount resets locals but the store survives, so this keeps
    // the regen sequence (42 → 43 → 44 ...) deterministic and walkthrough-
    // friendly even if the user navigates away and back.
    const nextSeed = $cohort.seed + 1
    cohort.set(generateCohort({
      model: $bundle.model,
      meanCodesPerDoc: $bundle.corpusStats.mean_codes_per_doc,
      n: COHORT_N,
      seed: nextSeed,
      nNeighbors: NEIGHBORS,
      qualityByPhenotype: $bundle.phenotypes.phenotypes.map((p) => p.quality),
    }))
    // Selection no longer points at a valid patient after regenerate;
    // let the reactive block above pick patients[0].
    selectedPatientId.set(null)
  }
</script>

<svelte:window on:click={(e) => {
  if (whatIsOpen && whatIsEl && !whatIsEl.contains(e.target as Node)) {
    whatIsOpen = false
  }
}} />

<section class="patient">
  <header class="section-head">
    <div class="title-block">
      <div class="title-row">
        <h1>Patient Atlas</h1>
        <details class="what-is" bind:this={whatIsEl} bind:open={whatIsOpen}>
          <summary>What's a synthetic patient?</summary>
          <div class="what-is-body popover">
            <p>
              <strong>These are not real people.</strong> Each "patient" here
              is generated by sampling from the phenotype model: first a mix
              of phenotypes (the <em>profile</em>), then a bag of conditions
              consistent with that mix.
            </p>
            <p>
              The conditions a patient is shown with are <em>unordered</em> —
              they're the set of things that happened in this patient's
              record over a time period, not a timeline. Counts are how
              often a code appeared in that record.
            </p>
            <p>
              Patients sit in the same 2D space as the phenotype atlas.
              A patient concentrated on one phenotype lands near that
              phenotype's bubble; a patient mixing several lands between
              them. Click a dot to inspect one.
            </p>
          </div>
        </details>
      </div>
      <p class="kicker">
        Each dot is a synthetic patient drawn from the model. Patients
        near each other share a similar mix of phenotypes.
      </p>
    </div>
    <div class="controls">
      <div class="control-stack">
        <ConditionSearch entityLabel="patients" />
        {#if $searchedPhenotypeForPatients !== null}
          <div class="phenotype-chip" title="Patients carrying this phenotype are ringed in amber on the atlas and have an amber right-band in the table">
            <span class="chip-label">Highlighting patients with</span>
            <span class="chip-val">{$phenotypesById.get($searchedPhenotypeForPatients)?.label || `Phenotype ${$searchedPhenotypeForPatients}`}</span>
            <button class="chip-clear" type="button" on:click={() => searchedPhenotypeForPatients.set(null)} title="Clear">×</button>
          </div>
        {/if}
      </div>
      <button class="btn-ghost regen" on:click={regenCohort}
        title="Re-roll the synthetic cohort with a new random seed">
        ↻ regenerate cohort
      </button>
    </div>
  </header>

  <div class="grid">
    <div class="left-col">
      <PatientMap />
      <PatientBrowser />
    </div>

    <div class="right-col">
      {#if current}
        <div class="profile-block">
          <header class="profile-head">
            <div class="eyebrow-row">
              <!-- Selection dot uses the patient's dominant-phenotype hue
                   so it visually matches the patient's atlas dot - "this
                   detail is about that dot". -->
              <span class="sel-dot" style="background: {dotColor}; box-shadow: 0 0 0 2px color-mix(in srgb, {dotColor} 28%, transparent);" aria-hidden="true"></span>
              <span class="eyebrow">Patient</span>
            </div>
            <h2 class="title">Patient {current.id}</h2>
            <p class="profile-sub">Phenotype profile · click a band below to see which of this patient's codes contributed to it.</p>
          </header>
          <ProfileBar
            theta={current.theta}
            codeBag={current.code_bag}
            height={44}
            onSelect={(k) => selectedPhenotypeId.set(k)}
          />
        </div>
        <ContributingCodes theta={current.theta} codeBag={current.code_bag} />
        <NeighborRibbon neighbors={current.neighbors} />
      {:else}
        <p class="empty">Click a patient on the atlas to see their details.</p>
      {/if}
    </div>
  </div>
</section>

<style>
  .patient { padding: 0.25rem 0 3rem; }

  .section-head {
    display: grid;
    grid-template-columns: 1fr auto;
    align-items: end;
    gap: 2rem;
    padding-bottom: 1.5rem;
    margin-bottom: 1.5rem;
    border-bottom: 1px solid var(--rule);
  }
  .title-block { display: flex; flex-direction: column; gap: 0.45rem; }
  .title-block h1 { margin: 0.1rem 0 0; }
  .title-row {
    display: flex;
    align-items: baseline;
    gap: 1rem;
    flex-wrap: wrap;
    position: relative;
  }
  .kicker {
    margin: 0.25rem 0 0;
    font-size: var(--fs-small);
    color: var(--ink-muted);
    max-width: 62ch;
    line-height: 1.55;
  }

  .what-is { position: relative; }
  .what-is summary {
    cursor: pointer;
    color: var(--accent);
    font-size: var(--fs-small);
    list-style: none;
    display: inline-block;
    border-bottom: 1px dotted var(--accent);
    text-underline-offset: 2px;
  }
  .what-is summary::-webkit-details-marker { display: none; }
  .what-is summary::marker { display: none; }
  .what-is summary:hover {
    color: var(--ink);
    border-bottom-color: var(--ink);
  }
  .what-is[open] summary {
    color: var(--ink);
    border-bottom-color: transparent;
  }
  .what-is-body {
    margin-top: 0.6rem;
    max-width: 62ch;
    padding: 0.85rem 1rem;
    background: var(--surface);
    border: 1px solid var(--rule);
    border-left: 3px solid var(--accent);
    border-radius: var(--radius-sm);
  }
  .what-is-body.popover {
    position: absolute;
    top: 1.6rem;
    left: 0;
    z-index: 5;
    width: 62ch;
    max-width: min(62ch, calc(100vw - 4rem));
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
  }
  .what-is-body p {
    margin: 0 0 0.55rem;
    font-size: var(--fs-small);
    color: var(--ink-muted);
    line-height: 1.6;
  }
  .what-is-body p:last-child { margin-bottom: 0; }
  .what-is-body em { font-style: italic; color: var(--ink); }
  .what-is-body strong {
    color: var(--ink);
    font-weight: 600;
  }

  .controls {
    display: flex;
    align-items: end;
    gap: 1.25rem;
  }
  .control-stack {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    align-items: flex-end;
  }
  .regen { font-family: var(--font-body); font-size: var(--fs-small); }
  .regen:hover { color: var(--accent); }

  .phenotype-chip {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    padding: 0.25rem 0.55rem;
    background: var(--accent-find-soft);
    border-radius: var(--radius-sm);
    font-size: var(--fs-micro);
    color: var(--accent-find-ink);
    max-width: 280px;
    box-shadow: inset 3px 0 0 var(--accent-find);
  }
  .phenotype-chip .chip-label {
    font-family: var(--font-mono);
    text-transform: uppercase;
    letter-spacing: 0.06em;
    opacity: 0.85;
  }
  .phenotype-chip .chip-val {
    font-weight: 600;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .phenotype-chip .chip-clear {
    border: 0;
    background: transparent;
    color: var(--accent-find-ink);
    cursor: pointer;
    font-size: 1rem;
    line-height: 1;
    padding: 0 0.1rem;
    margin-left: 0.1rem;
  }
  .phenotype-chip .chip-clear:hover { color: var(--ink); }

  .grid {
    display: grid;
    grid-template-columns: 1.1fr 1fr;
    gap: 1.5rem;
    align-items: start;
  }
  .left-col, .right-col {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
    min-width: 0;
  }

  .profile-block {
    background: var(--surface);
    border: 1px solid var(--rule);
    border-radius: var(--radius-sm);
    padding: 1.25rem 1.25rem 1rem;
  }
  .profile-head {
    display: flex;
    flex-direction: column;
    gap: 0.45rem;
    padding-bottom: 1rem;
    margin-bottom: 1rem;
    border-bottom: 1px solid var(--rule);
  }
  .eyebrow-row {
    display: flex;
    align-items: center;
    gap: 0.45rem;
  }
  .sel-dot {
    display: inline-block;
    width: 9px;
    height: 9px;
    border-radius: 50%;
    background: var(--accent);
    box-shadow: 0 0 0 2px var(--accent-faint);
  }
  .profile-head .title {
    font-size: 1.4rem;
    font-weight: 600;
    letter-spacing: var(--tracking-display);
    line-height: 1.15;
    color: var(--ink);
    font-family: var(--font-mono);
    margin: 0;
  }
  .profile-sub {
    margin: 0.15rem 0 0;
    font-size: var(--fs-micro);
    color: var(--ink-faint);
    font-style: italic;
  }
  .empty {
    color: var(--ink-faint);
    font-style: italic;
    padding: 2rem 0;
  }
</style>
