"""Discover Verily Workbench resources and write export lines to .workspace_env.

Auto-detects GOOGLE_CLOUD_PROJECT, WORKSPACE_CDR, WORKSPACE_BUCKET, and
WORKSPACE_TEMP_BUCKET via the `wb` CLI. The CDR is often an external
read-only data project that is not surfaced by `wb resource list`, so a
manual override is supported via --cdr.

Output is a shell-sourceable file (default: .workspace_env in cwd) which
the Makefile recipes source before invoking spark-submit.

Usage:
    python3 setup_workspace.py
    python3 setup_workspace.py --cdr '<project>.<dataset>'
    python3 setup_workspace.py --out /tmp/env.sh
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


_VAR_ORDER = (
    "GOOGLE_CLOUD_PROJECT",
    "WORKSPACE_CDR",
    "WORKSPACE_BUCKET",
    "WORKSPACE_TEMP_BUCKET",
    "BUCKET",
)


def _wb(*args: str):
    """Run `wb <args> --format=json` and parse stdout as JSON."""
    cmd = ["wb", *args, "--format=json"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except FileNotFoundError:
        print("ERROR: 'wb' CLI not found on PATH. Are you on a Verily Workbench "
              "cluster?", file=sys.stderr)
        sys.exit(2)
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: `{' '.join(cmd)}` failed (exit {exc.returncode})",
              file=sys.stderr)
        if exc.stderr:
            print(exc.stderr, file=sys.stderr)
        sys.exit(2)
    return json.loads(proc.stdout)


def discover() -> dict[str, str]:
    """Pull workspace-shape values from the wb CLI."""
    out: dict[str, str] = {}

    workspace = _wb("workspace", "describe")
    out["GOOGLE_CLOUD_PROJECT"] = workspace["googleProjectId"]

    resources = _wb("resource", "list")
    for r in resources:
        rt = r.get("resourceType", "")
        if rt == "GCS_BUCKET":
            rid = r.get("id", "")
            bucket = r.get("bucketName")
            if not bucket:
                continue
            # Order matters — temp bucket id contains "workspace-bucket" too.
            if "temporary-workspace-bucket" in rid:
                out["WORKSPACE_TEMP_BUCKET"] = f"gs://{bucket}"
            elif "workspace-bucket" in rid:
                out["WORKSPACE_BUCKET"] = f"gs://{bucket}"
        elif rt in ("BQ_DATASET", "BIGQUERY_DATASET"):
            # First BQ resource wins — the user can override with --cdr if
            # the workspace ever has multiple BQ datasets attached.
            if "WORKSPACE_CDR" not in out:
                out["WORKSPACE_CDR"] = f"{r['projectId']}.{r['datasetId']}"
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--cdr", default=None,
        help=("manual override for WORKSPACE_CDR as <project>.<dataset>; use "
              "this when the CDR is an external read-only project not "
              "surfaced by `wb resource list`"),
    )
    parser.add_argument(
        "--out", default=".workspace_env",
        help="output file (default: .workspace_env in cwd)",
    )
    args = parser.parse_args(argv)

    discovered = discover()
    if args.cdr:
        discovered["WORKSPACE_CDR"] = args.cdr

    # Bare bucket name (no gs:// prefix), used by GCS-FUSE paths like
    # /mnt/gcs/$BUCKET/runs/<id>. The Makefile's fit-eval targets reference
    # $BUCKET directly so they can build a /mnt/gcs path the eval driver can
    # read back without an extra gs-strip step.
    ws_bucket = discovered.get("WORKSPACE_BUCKET", "")
    if ws_bucket.startswith("gs://"):
        discovered["BUCKET"] = ws_bucket[len("gs://"):]

    if not discovered.get("WORKSPACE_CDR"):
        print("ERROR: WORKSPACE_CDR not auto-discovered (no BQ_DATASET found "
              "in workspace resources). The CDR is often an external read-"
              "only project; pass it explicitly via:", file=sys.stderr)
        print("    make setup CDR='<project>.<dataset>'", file=sys.stderr)
        return 1
    if not discovered.get("GOOGLE_CLOUD_PROJECT"):
        print("ERROR: GOOGLE_CLOUD_PROJECT not discovered from `wb workspace "
              "describe`.", file=sys.stderr)
        return 1

    out_path = Path(args.out)
    lines = [
        "# Generated by setup_workspace.py — do not edit by hand.\n",
        "# Regenerate via: make setup  (optionally with CDR=<project>.<dataset>)\n",
    ]
    for k in _VAR_ORDER:
        v = discovered.get(k)
        if v:
            lines.append(f"export {k}='{v}'\n")
    out_path.write_text("".join(lines))

    summary = ", ".join(
        f"{k}={discovered[k]}" for k in _VAR_ORDER if discovered.get(k)
    )
    print(f"Wrote {out_path}: {summary}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
